apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-putter
  namespace: uniform-cluster
  labels:
    app: jms-putter
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: jms-putter
  template:
    metadata:
      labels:
        app: jms-putter
    spec:
      volumes:
        - name: ccdtfile
          configMap:
            name: ccdt
        - name: truststore
          secret:
            secretName: jms-client-truststore
        - name: keystore
          secret:
            secretName: jms-putter-keystore
      containers:
          - name: java
            image: image-registry.openshift-image-registry.svc:5000/uniform-cluster/jmstestapps:3
            imagePullPolicy: IfNotPresent
            command: ["java"]
            args: ["-cp", "/opt/app/mq-jms-ccdt-0.0.2.jar", "com.ibm.clientengineering.mq.samples.Putter"]
            volumeMounts:
              - name: ccdtfile
                mountPath: /opt/app/config
              - name: truststore
                mountPath: /opt/app/truststore.jks
                subPath: ca.jks
              - name: keystore
                mountPath: /opt/app/keystore.jks
                subPath: client.jks
