apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-uniform-cluster-mqsc-cm
  namespace: uniform-cluster
data:
  common_config.mqsc: |-
    define channel('+AUTOCL+_+QMNAME+') chltype(clusrcvr) trptype(tcp) conname(+CONNAME+) cluster('+AUTOCL+') replace

    define QL(APPQ1) cluster(DEMOCLUSTER) defbind(notfixed) clwluseq(any) maxdepth(99999999) replace
    define QL(APPQ2) cluster(DEMOCLUSTER) defbind(notfixed) clwluseq(any) maxdepth(99999999) replace

    DEFINE CHANNEL(DEF.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    SET CHLAUTH(DEF.SVRCONN) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
