apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: uniform-cluster-qm4
  namespace: uniform-cluster
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  queueManager:
    name: QM4
    ini:
      - configMap:
          items:
          - config.ini
          name: mq-uniform-cluster-ini-cm
    mqsc:
      - configMap:
          items:
          - common_config.mqsc
          name: mq-uniform-cluster-mqsc-cm
      - configMap:
          name: mq-uniform-cluster-qm4-mqsc-cm
          items:
            - qm4-config.mqsc

    ##################################################################

    availability:
      type: SingleInstance
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    route:
      enabled: true
    storage:
      queueManager:
        type: ephemeral
    # storage:
    #   defaultClass: ibmc-block-gold
    #   queueManager:
    #     deleteClaim: true
    #     type: persistent-claim
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      containers:
      - env:
        - name: MQSNOAUT
          value: "yes"
        name: qmgr
  web:
    enabled: true
  version: 9.2.5.0-r3
  pki:
    keys:
      - name: default
        secret:
          items:
            - tls.crt
            - tls.key
          secretName: mq-server-tls
    trust:
      - name: ca
        secret:
          items:
            - ca.crt
          secretName: mq-ca-tls
